import { readFileSync } from "node:fs";
const svg = readFileSync(process.env.TEMP + "/opencode/svg-actual.svg", "utf8");
const fills = {};
for (const m of svg.matchAll(/fill="#([0-9a-f]+)"/g)) fills[m[1]] = (fills[m[1]] ?? 0) + 1;
for (const [c, n] of Object.entries(fills).sort((a, b) => b[1] - a[1])) console.log("#" + c, n);
console.log("---");
const cuerpo = svg.match(/fill="#1f2328"[^>]*d="([^"]+)"/g) || [];
console.log("shapes con fill 1f2328:", cuerpo.length);
const negros = svg.match(/fill="#(?:000000|000|1f2328|24292f|111111|0a0a0a)"/g) || [];
console.log("fill negro:", negros.length);
console.log("---sample de style---");
const si = svg.indexOf(".typst-text");
console.log(svg.slice(si, si + 200));
console.log("---paths totales:", (svg.match(/<path /g) || []).length);
console.log("paths selfclosing:", (svg.match(/<path [^>]*\/>/g) || []).length);
console.log("paths open-close:", (svg.match(/<path [^>]*><\/path>/g) || []).length);