import { createTypstCompiler, loadFonts } from '@myriaddreamin/typst.ts';
import { createTypstRenderer } from '@myriaddreamin/typst.ts/renderer';
import { readFileSync, writeFileSync } from 'node:fs';
const dir = process.env.TEMP + '/opencode';
const getModule = (n) => () => fetch(new URL('file:///' + dir + '/app/public/wasm/' + n));
const fsbase = (n) => new Promise((r)=>fetch('file:///' + dir + '/app/public/wasm/' + n).then(x=>x.arrayBuffer()).then(r));
const lu = 'file:///' + dir + '/app/public/wasm/';
const comp = createTypstCompiler();
await comp.init({ getModule: getModule('typst_ts_web_compiler_bg.wasm'), beforeBuild: [loadFonts(['file:///' + dir + '/app/public/fonts/LiberationSans-Regular.ttf','file:///' + dir + '/app/public/fonts/LiberationSans-Bold.ttf'])] });
const ren = createTypstRenderer();
await ren.init({ getModule: getModule('typst_ts_renderer_bg.wasm'), beforeBuild: [loadFonts(['file:///' + dir + '/app/public/fonts/LiberationSans-Regular.ttf','file:///' + dir + '/app/public/fonts/LiberationSans-Bold.ttf'])] });
comp.addSource('/main.typ', readFileSync('D:/Gantt_typ/app/src/lib/plantilla.visualizacion.typ','utf8'));
comp.addSource('/gantt.typ', readFileSync('D:/Gantt_typ/app/gantt-lib/gantt.typ','utf8'));
comp.addSource('/datos.typ', readFileSync('D:/Gantt_typ/app/gantt-lib/datos.typ','utf8'));
comp.addSource('/dibujo.typ', readFileSync('D:/Gantt_typ/app/gantt-lib/dibujo.typ','utf8'));
comp.addSource('/fechas.typ', readFileSync('D:/Gantt_typ/app/gantt-lib/fechas.typ','utf8'));
comp.addSource('/cpm.typ', readFileSync('D:/Gantt_typ/app/gantt-lib/cpm.typ','utf8'));
comp.mapShadow('/datos.yaml', new TextEncoder().encode(readFileSync('D:/Gantt_typ/ejemplos/datos.yaml','utf8')));
const out = await comp.compile({ mainFilePath: '/main.typ', format: 'vector', diagnostics: 'full' });
const diag = (out.diagnostics??[]).map(d=>d.message);
console.log('diagnostics:', diag);
if (out.result) {
  const svg = await ren.renderSvg({ format: 'vector', artifactContent: out.result });
  writeFileSync(dir + '/svg-wasm.yaml', svg);
  console.log('svg bytes:', svg.length);
} else console.log('SIN RESULTADO');
